### ISSUE TITLE
How to run these examples?

### ISSUE THREAD

**Issue by tupini07** [planetis-m/raylib-examples#4]
Hi! I apologize if the answer for this is obvious, but as someone who is just starting to dabble in Nim I'm having some trouble finding out how to run these examples. Could you provide some guidance?

Thanks!

**Comment by planetis-m** [comment]
Hello @tupini07 and thank you fro trying out naylib. The installation steps is to first get [naylib](https://github.com/planetis-m/naylib) ($ nimble install naylib) and then `nim c -d: release example.nim` each individual example.

**Comment by tupini07** [comment]
thank you very much! Closing

**Comment by IzumiGoshi** [comment]
Could you add an example for how to compile the web example? 
`nim c -d: release basic_window_web.nim`  seems to still build a desktop version. 
Sorry if I'm missing something fundamental, I'm new to using nim. 
Thanks.
